export const GET_KEY_FIN_RATIOS = 'GET_KEY_RATIOS'
export const GET_COMPANY_LOGO = 'GET_COMPANY_LOGO'
export const GET_COMPANY_NAME = 'GET_COMPANY_NAME'
export const GET_COMPANY_STATS = 'GET_COMPANY_STATS'
